import {test,expect} from '@playwright/test';import path from 'node:path';import fs from 'node:fs/promises';
test('five-passage demo, changed word, page preview, exports, clear',async({page})=>{const external=[],errors=[];page.on('request',req=>{if(!new URL(req.url()).hostname.match(/^(127\.0\.0\.1|localhost)$/))external.push(req.url());});page.on('pageerror',err=>errors.push(err.message));await page.goto('/');await page.getByRole('button',{name:/Try the synthetic demo/}).click();await expect(page.locator('#results-section')).toBeVisible();await expect(page.locator('.result-item')).toHaveCount(5);await expect(page.locator('.result-item').nth(0)).toContainText('page moved');await expect(page.locator('.result-item').nth(1)).toContainText('Whitespace-normalized match');await page.locator('.result-item').nth(2).click();await expect(page.locator('.word-diff ins')).toContainText('not');await page.locator('.page-preview summary').first().click();await expect(page.locator('.page-preview').first().locator('p')).not.toHaveText('Loading page…');await expect(page.locator('.page-preview canvas').first()).toBeVisible();const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download JSON'}).click()]);const parsed=JSON.parse(await fs.readFile(await download.path(),'utf8'));expect(parsed.results.map(x=>x.targetStatus)).toEqual(['literal_match','normalized_match','possible_changed_passage','multiple_matches','not_located']);const [html]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download HTML'}).click()]);const source=await fs.readFile(await html.path(),'utf8');expect(source).toContain('Unverified suggestions');expect(source).not.toContain('<script');await page.getByRole('button',{name:'Clear everything'}).click();await expect(page.locator('#results-section')).toBeHidden();await expect(page.locator('#quote-cards textarea')).toHaveValue('');expect(external).toEqual([]);expect(errors).toEqual([]);});
test('local uploads make only same-origin static asset requests',async({page})=>{await page.goto('/');await page.waitForLoadState('networkidle');const unexpected=[];await page.route('**/*',route=>{const request=route.request(),url=new URL(request.url());if(url.origin==='http://127.0.0.1:4173'&&request.method()==='GET'&&/^\/(assets|pdfjs)\//.test(url.pathname)&&!url.search)return route.continue();unexpected.push(request.url());return route.abort();});await page.locator('#old-file').setInputFiles(path.resolve('public/demo/old-handbook.pdf'));await page.locator('#new-file').setInputFiles(path.resolve('public/demo/new-handbook.pdf'));await page.locator('#quote-file').setInputFiles(path.resolve('public/demo/saved-quotes.txt'));await expect(page.locator('#import-status')).toContainText('5 passages accepted');await page.getByRole('button',{name:/Compare saved passages/}).click();await expect(page.locator('#results-section')).toBeVisible();await expect(page.locator('.result-item')).toHaveCount(5);expect(unexpected).toEqual([]);});
test('import preview, edit invalidates results, repeat demo, no horizontal overflow',async({page})=>{await page.goto('/');await page.locator('#quote-file').setInputFiles({name:'quotes.txt',mimeType:'text/plain',buffer:Buffer.from('First short quote.\n\n'+('x'.repeat(2001))+'\n\nSecond short quote.')});await expect(page.locator('#import-status')).toContainText('2 passages accepted, 1 oversized blocks skipped');await expect(page.locator('#quote-cards textarea')).toHaveCount(2);await page.getByRole('button',{name:/Try the synthetic demo/}).click();await expect(page.locator('#results-section')).toBeVisible();await page.locator('#quote-cards textarea').first().fill('An edited quote.');await expect(page.locator('#results-section')).toBeHidden();await page.getByRole('button',{name:/Try the synthetic demo/}).click();await expect(page.locator('.result-item')).toHaveCount(5);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);});
test('cancel and reset do not restore stale results',async({page})=>{await page.addInitScript(()=>{const read=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){await new Promise(resolve=>setTimeout(resolve,250));return read.call(this);};});await page.goto('/');await page.getByRole('button',{name:/Try the synthetic demo/}).click();await expect(page.locator('#results-section')).toBeVisible();await page.getByRole('button',{name:/Compare saved passages/}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('#progress')).toContainText('cancelled');await expect(page.locator('#results-section')).toBeHidden();await page.getByRole('button',{name:/Compare saved passages/}).click();await page.getByRole('button',{name:'Clear everything'}).click();await expect(page.locator('#progress')).toContainText('Cleared');await expect(page.locator('#results-section')).toBeHidden();});

test('clear followed immediately by a new demo keeps the new result',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Try the synthetic demo/}).click();await expect(page.locator('#results-section')).toBeVisible();await page.getByRole('button',{name:'Clear everything'}).click();await page.getByRole('button',{name:/Try the synthetic demo/}).click();await expect(page.locator('#results-section')).toBeVisible();await expect(page.locator('.result-item')).toHaveCount(5);await expect(page.locator('#old-name')).toContainText('old-handbook.pdf');await expect(page.locator('#demo')).toBeEnabled();});


test('capture reviewed layout and reopen the exported HTML',async({page,context},testInfo)=>{
 await page.goto('/');
 await expect(page.getByRole('link',{name:'Source & feedback'})).toHaveAttribute('href','https://github.com/mozzie49/quotecarry');
 await page.screenshot({path:testInfo.outputPath('landing.png'),fullPage:true});
 await page.getByRole('button',{name:/Try the synthetic demo/}).click();
 await expect(page.locator('#results-section')).toBeVisible();
 await page.locator('.result-item').nth(2).click();
 await page.locator('.page-preview summary').first().click();
 await expect(page.locator('.page-preview').first().locator('p')).not.toHaveText('Loading page…');
 await expect(page.locator('.page-preview').first().locator('p')).not.toContainText('unavailable. Open');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
 await page.screenshot({path:testInfo.outputPath('changed-preview.png'),fullPage:true});
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download HTML'}).click()]);
 const reportPath=testInfo.outputPath('quotecarry-report.html');
 await download.saveAs(reportPath);
 const report=await context.newPage();
 await report.goto('file://'+reportPath);
 await expect(report.getByRole('heading',{name:'Your saved passages, across revisions'})).toBeVisible();
 await expect(report.getByRole('heading',{name:'Unverified suggestions'})).toBeVisible();
 expect(await report.locator('script').count()).toBe(0);
 expect(await report.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
 await report.screenshot({path:testInfo.outputPath('reopened-report.png'),fullPage:true});
 await report.close();
});
