import {test} from 'node:test';
import assert from 'node:assert/strict';
import {compareQuote,findMatches,normalizeWithMap,wordDiff} from '../src/match.mjs';
const q='The estimate applies only to the tested sample.';
const compare=(oldPages,newPages,quote=q,options)=>compareQuote(oldPages,newPages,quote,options);
test('literal quote',()=>assert.equal(compare([q],[q]).targetStatus,'literal_match'));
test('moved independent badge',()=>assert.equal(compare([q],['Introduction',q]).pageMoved,true));
test('line wrap maps to exact raw span',()=>{const raw='Prefix. '+q.replace('only to','only\r\n\tto')+' Suffix.';const m=findMatches([raw],q)[0];assert.equal(raw.slice(m.start,m.end),m.text);assert.equal(m.text,q.replace('only to','only\r\n\tto'));assert.equal(m.kind,'normalized');});
test('NBSP map and leading trim',()=>{const map=normalizeWithMap(' \tA\u00a0  B\n');assert.equal(map.text,'A B');assert.deepEqual(map.starts,[2,3,6]);assert.deepEqual(map.ends,[3,6,7]);});
test('negation only becomes candidate',()=>{const r=compare([q],[q.replace('applies','does not apply')]);assert.equal(r.targetStatus,'possible_changed_passage');assert.ok(r.candidates[0].diff.some(x=>x.type==='insert'&&x.text.includes('not')));});
test('changed number not accepted',()=>assert.equal(findMatches(['The result is 45 percent.'],'The result is 54 percent.').length,0));
test('failed baseline blocks positive',()=>assert.equal(compare(['Nothing relevant'],[q]).targetStatus,'not_evaluated'));
test('baseline duplicates',()=>assert.equal(compare([q,q],[q]).baselineStatus,'baseline_ambiguous'));
test('baseline human selection recorded',()=>{const before=findMatches([q,q],q);const r=compare([q,q],[q],q,{selectedOldId:before[1].id});assert.equal(r.baselineStatus,'baseline_ambiguous');assert.equal(r.targetStatus,'literal_match');assert.equal(r.selectedOldId,before[1].id);});
test('hint never resolves baseline ambiguity',()=>assert.equal(compare([q,q],[q],{quote:q,pageHint:1}).targetStatus,'not_evaluated'));
test('new duplicates distant pages',()=>assert.equal(compare([q],[q,'gap',q]).targetStatus,'multiple_matches'));
test('exact and normalized occurrence both count',()=>assert.equal(compare([q],[q,q.replace('only to','only\nto')]).targetStatus,'multiple_matches'));
test('same page duplicate',()=>assert.equal(findMatches([q+' '+q],q).length,2));
test('hyphen preserved',()=>assert.equal(findMatches(['A long-term observation.'],'A longterm observation.').length,0));
test('line-end hyphen preserved',()=>assert.equal(findMatches(['A long-\nterm observation.'],'A longterm observation.').length,0));
test('ligature preserved',()=>assert.equal(findMatches(['The ﬁnal observations.'],'The final observations.').length,0));
test('no cross page stitching',()=>assert.equal(findMatches(['The estimate applies','only to the tested sample.'],q).length,0));
test('case significant',()=>assert.equal(findMatches([q.toUpperCase()],q).length,0));
test('short quote carries warning',()=>assert.match(compare(['estimate'],['estimate'],'estimate').warnings[0],/Short/));
test('overlength and empty rejected',()=>{assert.throws(()=>findMatches([q],''));assert.throws(()=>findMatches([q],'a'.repeat(2001)));});
test('occurrence cap explicit',()=>assert.throws(()=>findMatches([q.repeat(101)],q)));
test('substring inside word blocked',()=>assert.equal(findMatches(['unavailable'],'available').length,0));
test('substring inside number blocked',()=>assert.equal(findMatches(['150'],'15').length,0));
test('unicode combining mark boundary',()=>assert.equal(findMatches(['cafe\u0301'],'cafe').length,0));
test('unicode letter and numeric boundary',()=>{assert.equal(findMatches(['éavailable'],'available').length,0);assert.equal(findMatches(['15²'],'15').length,0);});
test('punctuated whole words accepted',()=>assert.equal(findMatches(['(available)'],'available').length,1));
test('context negation visible despite exact quote',()=>{const r=compare(['Evidence supports this. '+q],['Evidence does not support this. '+q]);assert.equal(r.targetStatus,'literal_match');assert.equal(r.contextStatus,'context_changed');});
test('partial revised blocks unique',()=>{const r=compare([q],{complete:false,pages:[q],warnings:['blank page']});assert.equal(r.targetStatus,'source_unavailable');assert.equal(r.after.length,1);});
test('partial revised blocks negative',()=>assert.equal(compare([q],{complete:false,pages:['other']}).targetStatus,'source_unavailable'));
test('partial old blocks unique',()=>assert.equal(compare({complete:false,pages:[q]},[q]).baselineStatus,'baseline_unavailable'));
test('identical bytes warning',()=>assert.match(compare({complete:true,pages:[q],sha256:'abc'},{complete:true,pages:[q],sha256:'abc'}).warnings[0],/identical/));
test('physical index separate from ambiguous label',()=>{const r=compare([{index:2,label:'i',text:q}],[{index:5,label:'i',text:q}]);assert.equal(r.pageMoved,true);assert.equal(r.after[0].label,'i');});
test('stable repeat results',()=>{const a=compare([q],[q.replace('applies','does not apply')]);assert.deepEqual(a,compare([q],[q.replace('applies','does not apply')]));});
test('word diff preserves changed numeric evidence',()=>assert.deepEqual(wordDiff('There are 15 reports.','There are 150 reports.').filter(x=>x.type!=='equal'),[{type:'insert',text:'150'},{type:'delete',text:'15'}]));
test('candidate windows cannot cross hard layout boundaries',()=>{const old=[q];const text=q.replace('applies','does not apply');const page={index:1,text,breaks:[text.indexOf('only')]};assert.equal(compare(old,[page]).targetStatus,'not_located');});
test('swapping a source pair cannot validate a quote absent from that baseline',()=>{const original='Original-only passage used in this source.',revised='A different revised passage is present instead.';const r=compareQuote([revised],[original],original);assert.equal(r.baselineStatus,'baseline_not_located');assert.equal(r.targetStatus,'not_evaluated');assert.equal(r.after.length,1);});
test('cached page mappings refresh if extracted text changes',()=>{const page={index:1,text:q};assert.equal(findMatches([page],q).length,1);page.text='No matching passage here.';assert.equal(findMatches([page],q).length,0);});
