import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import {writeFile,mkdir} from 'node:fs/promises';
const out=new URL('../public/demo/',import.meta.url);await mkdir(out,{recursive:true});
export const quotes=[
'Completed uploads remain available for seven days after review.',
'The review queue preserves the original order of submitted reports.',
'Failed imports are retried automatically before the next review.',
'Reviewers can export the full list of pending comments.',
'Each archived report keeps its original reviewer notes.'
];
const intro=['This handbook is a synthetic demonstration for QuoteCarry.', 'Every policy and workflow described here is fictional.', 'Use these pages to inspect quotation movement and revision.', 'They are not documentation for a real organization or product.'];
async function make(name,version,pages){const pdf=await PDFDocument.create();pdf.setTitle(`Field Notes Review Handbook - ${version} (synthetic)`);pdf.setAuthor('QuoteCarry synthetic fixtures');pdf.setSubject('Original fictional text for controlled quotation comparison');pdf.setCreationDate(new Date('2026-10-01T00:00:00Z'));pdf.setModificationDate(new Date('2026-10-01T00:00:00Z'));const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);
for(const [i,lines] of pages.entries()){const p=pdf.addPage([612,792]);p.drawRectangle({x:0,y:742,width:612,height:50,color:rgb(.07,.23,.25)});p.drawText('FIELD NOTES / REVIEW HANDBOOK',{x:48,y:760,size:12,font:bold,color:rgb(1,1,1)});p.drawText(`${version.toUpperCase()} - SYNTHETIC DEMO`,{x:48,y:696,size:10,font:bold,color:rgb(.15,.42,.42)});let y=649;for(const line of lines){p.drawText(line,{x:48,y,size:12,font,color:rgb(.12,.18,.21)});y-=line?25:18;}p.drawText(`Synthetic fixture  |  PDF page ${i+1}`,{x:48,y:42,size:9,font,color:rgb(.4,.45,.45)});}await writeFile(new URL(name,out),await pdf.save());}
await make('old-handbook.pdf','original',[intro,['1. Preparing the review','', 'Review windows follow a fixed schedule.',quotes[0],'', 'Reports arrive through a single submission inbox.',quotes[1],'', 'The following rule describes the import process.',quotes[2],'', 'Review staff should check this section after each update.'],['2. Comments and archives','','The comments panel has a dedicated export action.',quotes[3],'', 'Archived material remains read-only.',quotes[4],'', 'The archive section concludes this synthetic handbook.']]);
await make('new-handbook.pdf','revised',[intro,['New introduction','','This page was inserted in the revised synthetic handbook.','It explains how revisions should be reviewed by the reader.','A page insertion changes physical PDF page indices.','It does not necessarily change the words of a saved passage.'],['1. Preparing the review','','Review windows follow a fixed schedule.',quotes[0],'','Reports arrive through a single submission inbox.','The review queue preserves the original','order of submitted reports.','','The following rule describes the import process.','Failed imports are not retried automatically before the next review.','','The comments panel has a dedicated export action.',quotes[3]],['2. Comments and archives','','A second copy of the export rule appears here.',quotes[3],'','The archive section was rewritten for this revision.','Previous notes are discussed outside this synthetic handbook.']]);
await writeFile(new URL('saved-quotes.txt',out),quotes.join('\n\n')+'\n');
await writeFile(new URL('README.txt',out),'QuoteCarry original synthetic demonstration. MIT licensed.\nThese fictional policies describe no real organization or product.\nExpected: moved literal; reflowed whitespace; changed negation; duplicated; not located.\nGenerated with scripts/generate-demo.mjs and pdf-lib 1.17.1.\n');
console.log('Generated original synthetic demo PDFs and quote list.');
