import './style.css';
import {compareQuote,LIMITS} from './match.mjs';
import {extractPdf,renderPage} from './pdf.mjs';
import {buildReport,reportHtml,STATUS_LABELS} from './report.mjs';
const $=id=>document.getElementById(id);
function el(tag,text,className){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(className)e.className=className;return e;}
function button(text,fn,className='button'){const b=el('button',text,className);b.type='button';b.addEventListener('click',fn);return b;}
const state={files:[null,null],docs:[],quotes:[{id:'q1',quote:'',label:'',note:'',pageHint:null}],results:[],selected:0,selections:new Map(),controller:null,run:0,nextId:2};
$('app').innerHTML=`<header class="topbar"><a class="brand" href="#"><span class="brandmark" aria-hidden="true">”</span>QuoteCarry</a><span class="version">EXPERIMENTAL · 0.1 ALPHA</span><span class="privacy"><span aria-hidden="true">●</span> Your PDFs stay in this browser</span></header>
<main><section class="hero"><div><p class="eyebrow">A SMALL TOOL FOR CHANGING SOURCES</p><h1>New revision.<br><span>Same saved passages?</span></h1><p class="intro">Bring two PDFs and the quotes you care about. See what still appears, what moved, and what needs a closer look.</p></div><div class="demo-card"><div class="demo-icon" aria-hidden="true">“<span>→</span>”</div><h2>See the five-passage demo</h2><p>One passage moves. One reflows. One gains a “not.” Two need a closer look.</p><button class="button primary" id="demo">Try the synthetic demo <span aria-hidden="true">↗</span></button><a href="./demo/saved-quotes.txt" download>Download the sample quotes</a></div></section>
<div class="notice"><strong>Text evidence, with limits.</strong> This prototype compares extracted text, not meaning or citation validity. Latin-script, mostly single-column PDFs work best. No OCR or annotation transfer.</div>
<section class="setup" aria-labelledby="setup-title"><div class="section-title"><div><p class="eyebrow">01 / ADD YOUR SOURCES</p><h2 id="setup-title">Two versions. Your selected words.</h2></div><button class="text-button" id="reset">Clear everything</button></div><div class="source-grid"><label class="file-card"><span class="step">A</span><span class="file-title">Old PDF</span><span class="muted">The version you saved the quote from</span><input id="old-file" type="file" accept=".pdf,application/pdf"><span id="old-name" class="filename">Choose a PDF</span></label><div class="source-arrow" aria-hidden="true">→</div><label class="file-card"><span class="step">B</span><span class="file-title">Revised PDF</span><span class="muted">The version you want to check</span><input id="new-file" type="file" accept=".pdf,application/pdf"><span id="new-name" class="filename">Choose a PDF</span></label></div><p class="limits">Up to 25 MiB and 100 PDF pages per file. Files are processed in memory. Nothing is uploaded or saved in browser storage.</p>
<div class="quote-heading"><h3>Saved passages <span id="quote-count">1 / 50</span></h3><div class="actions"><label class="button secondary import-button">Import .txt<input type="file" id="quote-file" accept=".txt,text/plain"></label><button class="button secondary" id="add-quote">+ Add passage</button></div></div><p class="muted small">One exact quotation per card, up to 2,000 characters. Text imports use blank lines between passages and always open here for review.</p><p id="import-status" class="import-status" role="status"></p><div id="quote-cards"></div><div class="run-row"><button id="compare" class="button primary">Compare saved passages <span aria-hidden="true">→</span></button><button id="cancel" class="button secondary" hidden>Cancel</button><p id="progress" role="status" aria-live="polite">Review the inputs, then compare</p></div><p id="error" class="error" role="alert" hidden></p></section>
<section id="results-section" class="results" hidden aria-labelledby="results-title"><div class="section-title"><div><p class="eyebrow">02 / REVIEW THE EVIDENCE</p><h2 id="results-title">Your passage review</h2></div><div class="actions"><button id="export-html" class="button secondary">Download HTML</button><button id="export-json" class="button secondary">Download JSON</button></div></div><p class="muted small">Reports contain the quoted content, notes, file names and hashes. Review them before sharing. Source PDFs are not embedded.</p><div id="source-warnings"></div><div id="summary" class="summary"></div><div class="workspace"><nav id="result-list" class="result-list" aria-label="Passage results"></nav><div id="detail" class="detail" aria-live="polite"></div></div></section>
<section class="how"><p class="eyebrow">BUILT TO SAY “LOOK CLOSER”</p><div class="how-grid"><div><h3>Whitespace is the only shortcut</h3><p>Line breaks, tabs and repeated spaces may normalize. Case, punctuation, numbers and hyphens stay meaningful.</p></div><div><h3>Ambiguity stays visible</h3><p>Repeated text and incomplete extraction never become a single-occurrence result. Page hints don’t silently pick an occurrence.</p></div><div><h3>You remain the reader</h3><p>A changed context can change a claim. Check the PDF preview and original source before relying on a passage.</p></div></div></section></main><footer><a class="brand" href="#">QuoteCarry</a><span>Original synthetic demo · Open-source prototype · No accounts, keys or analytics</span><a class="source-link" href="https://github.com/mozzie49/quotecarry" target="_blank" rel="noopener noreferrer">Source & feedback ↗</a><details><summary>Privacy & limitations</summary><p>All PDF parsing and matching happens in your browser. The page loads its own JavaScript, PDF.js assets and optional synthetic demo files from this site. No uploaded-file content is sent anywhere. This app uses no local storage, telemetry, third-party fonts, or PDF links. Close or clear the page to release loaded documents. Your browser or device may retain downloaded reports.</p><p>Scanned PDFs, OCR fidelity, complex layouts, page-spanning quotations and non-Latin text are not supported. Some layout or extraction errors cannot be detected. Candidate search is bounded and can miss a changed passage. A SHA-256 hash identifies file bytes, not source authenticity or what an AI read. No broad accuracy or usefulness claim has been validated.</p></details></footer>`;
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function invalidate(){state.results=[];state.selections.clear();$('results-section').hidden=true;error('');}
function quoteCards(){const root=$('quote-cards');root.replaceChildren();$('quote-count').textContent=`${state.quotes.length} / ${LIMITS.quotes}`;
 state.quotes.forEach((q,i)=>{const card=el('div',null,'quote-card'),head=el('div',null,'card-head');head.append(el('strong',`PASSAGE ${String(i+1).padStart(2,'0')}`),button('Remove',()=>{state.quotes.splice(i,1);if(!state.quotes.length)state.quotes.push({id:`q${state.nextId++}`,quote:'',label:'',note:'',pageHint:null});invalidate();quoteCards();},'text-button'));const label=el('label',null,'sr-only');label.htmlFor=`quote-${q.id}`;label.textContent=`Passage ${i+1} text`;const area=el('textarea');area.id=`quote-${q.id}`;area.value=q.quote;area.maxLength=2000;area.rows=3;area.placeholder='Paste the exact words you saved…';area.addEventListener('input',()=>{q.quote=area.value;invalidate();});const metadata=el('details',null,'metadata');metadata.append(el('summary','Add a label, note or old-page hint'));const fields=el('div',null,'metadata-fields');for(const [key,title,type]of[['label','Label','text'],['note','Private note','text'],['pageHint','Old PDF page hint','number']]){const l=el('label',title);const input=el('input');input.type=type;input.value=q[key]??'';input.maxLength=key==='note'?1000:160;if(type==='number'){input.min='1';input.max='100';}input.addEventListener('input',()=>{q[key]=type==='number'?(input.value?Number(input.value):null):input.value;invalidate();});l.append(input);fields.append(l);}metadata.append(fields);card.append(head,label,area,metadata);root.append(card);});}
function setFile(index,file){state.files[index]=file;$(index?'new-name':'old-name').textContent=file?`${file.name} · ${(file.size/1024/1024).toFixed(2)} MiB`:'Choose a PDF';invalidate();}
$('old-file').addEventListener('change',e=>setFile(0,e.target.files[0]||null));$('new-file').addEventListener('change',e=>setFile(1,e.target.files[0]||null));
$('add-quote').addEventListener('click',()=>{if(state.quotes.length>=50){error('The prototype supports at most 50 passages.');return;}state.quotes.push({id:`q${state.nextId++}`,quote:'',label:'',note:'',pageHint:null});invalidate();quoteCards();$('quote-cards').lastChild.querySelector('textarea').focus();});
function importText(text){const blocks=text.replace(/^\uFEFF/u,'').replace(/\r\n?/gu,'\n').split(/\n[\t ]*\n+/u).map(x=>x.trim()).filter(Boolean);if(blocks.length>50)throw new Error(`Import has ${blocks.length} passages; the limit is 50. Nothing was imported.`);const accepted=blocks.filter(x=>x.length<=2000),skipped=blocks.length-accepted.length;if(!accepted.length)throw new Error('No supported passages found. Use non-empty blocks of at most 2,000 characters.');state.quotes=accepted.map(quote=>({id:`q${state.nextId++}`,quote,label:'',note:'',pageHint:null}));invalidate();quoteCards();$('import-status').textContent=`Import preview: ${accepted.length} passages accepted, ${skipped} oversized blocks skipped. Review and edit every card before comparing.`;}
$('quote-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>110000)throw new Error('Quote text file is too large. Maximum 110 KB.');const bytes=new Uint8Array(await file.arrayBuffer());importText(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch(err){error(err.message);}finally{e.target.value='';}});
function busy(value){$('cancel').hidden=!value;document.querySelectorAll('.setup input,.setup textarea,.setup button,.setup summary,#demo').forEach(e=>{if(e.id!=='cancel'&&e.id!=='reset'){if('disabled'in e)e.disabled=value;e.setAttribute('aria-disabled',String(value));}});$('demo').disabled=value;}
async function dispose(){const retired=state.docs;state.docs=[];for(const doc of retired)await doc?.dispose?.().catch(()=>{});}
async function compare(){const run=++state.run;state.controller?.abort();state.controller=new AbortController();const signal=state.controller.signal;invalidate();let loaded=[];
 try{if(!state.files.every(Boolean))throw new Error('Choose the old and revised PDF first.');if(state.quotes.some(q=>!q.quote.trim()))throw new Error('Fill in or remove every empty passage card.');if(state.quotes.some(q=>q.quote.length>2000))throw new Error('A passage exceeds 2,000 characters.');busy(true);await dispose();for(let i=0;i<2;i++){const doc=await extractPdf(state.files[i],signal,(page,total)=>{if(run===state.run)$('progress').textContent=`Reading ${i?'revised':'old'} PDF · page ${page} of ${total}`;});loaded.push(doc);if(run!==state.run||signal.aborted){await doc.dispose();return;}}state.docs=loaded;const results=[];for(const [index,q] of state.quotes.entries()){if(run!==state.run||signal.aborted)throw new DOMException('Cancelled','AbortError');$('progress').textContent=`Checking passage ${index+1} of ${state.quotes.length}`;results.push(compareQuote(loaded[0],loaded[1],q));await new Promise(resolve=>setTimeout(resolve,0));}if(run!==state.run||signal.aborted)throw new DOMException('Cancelled','AbortError');state.results=results;state.selected=0;showResults();$('progress').textContent=`Compared ${state.results.length} passages. Review the evidence below.`;$('results-section').scrollIntoView({behavior:'smooth',block:'start'});}catch(err){for(const doc of loaded)if(!state.docs.includes(doc))await doc.dispose().catch(()=>{});if(run===state.run){if(err.name==='AbortError'||signal.aborted)$('progress').textContent='Comparison cancelled. Your inputs are still here.';else{error(err.message||'The comparison could not finish.');$('progress').textContent='No complete comparison was produced.';}}}finally{if(run!==state.run)for(const doc of loaded)if(!state.docs.includes(doc))await doc.dispose().catch(()=>{});if(run===state.run){busy(false);state.controller=null;}}}
$('compare').addEventListener('click',compare);$('cancel').addEventListener('click',()=>{state.controller?.abort();$('progress').textContent='Cancelling…';});
$('reset').addEventListener('click',async()=>{state.run++;state.controller?.abort();state.controller=null;busy(false);void dispose();state.files=[null,null];$('old-file').value='';$('new-file').value='';setFile(0,null);setFile(1,null);state.quotes=[{id:`q${state.nextId++}`,quote:'',label:'',note:'',pageHint:null}];quoteCards();$('import-status').textContent='';$('progress').textContent='Cleared. Files and results are no longer held by the app.';});
$('demo').addEventListener('click',async()=>{const token=++state.run;state.controller?.abort();error('');$('demo').disabled=true;try{const base=import.meta.env.BASE_URL;const responses=await Promise.all(['old-handbook.pdf','new-handbook.pdf','saved-quotes.txt'].map(n=>fetch(`${base}demo/${n}`)));if(token!==state.run)return;if(responses.some(r=>!r.ok))throw new Error('The demo files could not be loaded. Try downloading the fixtures and selecting them manually.');const oldBlob=await responses[0].blob(),newBlob=await responses[1].blob(),quoteText=await responses[2].text();if(token!==state.run)return;$('old-file').value='';$('new-file').value='';setFile(0,new File([oldBlob],'old-handbook.pdf',{type:'application/pdf'}));setFile(1,new File([newBlob],'new-handbook.pdf',{type:'application/pdf'}));importText(quoteText);$('import-status').textContent='Synthetic demo: five original fictional passages loaded. These fixtures demonstrate controlled cases only.';await compare();}catch(err){if(token===state.run)error(err.message);}finally{if(token===state.run&&!state.controller)$('demo').disabled=false;}});
function tone(r){return r.targetStatus==='literal_match'||r.targetStatus==='normalized_match'?'located':r.targetStatus==='possible_changed_passage'?'changed':r.targetStatus==='multiple_matches'||r.baselineStatus==='baseline_ambiguous'?'ambiguous':'unlocated';}
function showResults(){$('results-section').hidden=false;const counts={located:0,changed:0,ambiguous:0,unlocated:0};for(const r of state.results)counts[tone(r)]++;$('summary').replaceChildren(...Object.entries(counts).map(([name,value])=>{const d=el('div',null,`summary-item ${name}`);d.append(el('strong',value),el('span',{located:'Located text',changed:'Possible change',ambiguous:'Ambiguous',unlocated:'Needs review'}[name]));return d;}));const warnings=$('source-warnings');warnings.replaceChildren();for(const [i,doc]of state.docs.entries())if(doc.warnings.length){const disclosure=el('details',null,'notice warning');disclosure.append(el('summary',`${i?'Revised':'Old'} PDF: ${doc.warnings.length} extraction/layout warning${doc.warnings.length===1?'':'s'}. Review before relying on the results.`));for(const w of doc.warnings)disclosure.append(el('p',w));warnings.append(disclosure);}renderList();renderDetail();}
function renderList(){const list=$('result-list');list.replaceChildren();state.results.forEach((r,i)=>{const b=button('',()=>{state.selected=i;renderList();renderDetail();},`result-item ${i===state.selected?'selected':''}`);b.setAttribute('aria-current',String(i===state.selected));const top=el('div',null,'result-top');top.append(el('span',`PASSAGE ${String(i+1).padStart(2,'0')}`),el('span',{located:'●',changed:'↔',ambiguous:'⋯',unlocated:'?'}[tone(r)],`result-symbol ${tone(r)}`));b.append(top,el('p',r.label||r.quote),el('span',STATUS_LABELS[r.targetStatus],`status-text ${tone(r)}`));if(r.pageMoved)b.append(el('span',' ↗ page moved','tiny'));list.append(b);});}
function badge(text,className=''){return el('span',text,`badge ${className}`);}
function contextBlock(context){const b=el('blockquote',null,'context');b.append(document.createTextNode(context.before),el('mark',context.quote),document.createTextNode(context.after));return b;}
function showOccurrence(container,doc,occ){const box=el('div',null,'occurrence');box.append(el('p',`PDF page ${occ.page} · embedded label ${occ.label??'unknown'} · raw span ${occ.start}–${occ.end}`,'small muted'),contextBlock(occ.context));if(occ.operations?.length)box.append(el('p',`Normalization: ${occ.operations.join(', ')}`,'small'));const expand=el('details',null,'page-preview');expand.append(el('summary','Open PDF page preview'));const canvas=el('canvas');canvas.setAttribute('aria-label',`PDF page ${occ.page} preview`);const note=el('p','Loading page…','small muted');expand.append(note,canvas);let rendered=false;expand.addEventListener('toggle',async()=>{if(!expand.open||rendered)return;rendered=true;try{const result=await renderPage(doc,occ.page,canvas,occ);note.textContent=result.highlighted?'Highlight follows whole extracted text runs. Confirm it against the page.':'Precise highlight unavailable. Compare the page with the raw extracted text above.';}catch{note.textContent='Page preview unavailable. Open the original PDF to inspect this location.';}});box.append(expand);container.append(box);}
function renderDetail(){const r=state.results[state.selected];if(!r)return;const root=$('detail');root.replaceChildren();const title=el('div',null,'detail-heading');title.append(el('p',`PASSAGE ${String(state.selected+1).padStart(2,'0')} / ${state.results.length}`,'eyebrow'),el('h3',STATUS_LABELS[r.targetStatus]));const tags=el('div',null,'badges');tags.append(badge(STATUS_LABELS[r.baselineStatus]));if(r.selectedOldId)tags.append(badge('Old occurrence selected by you'));if(r.pageMoved)tags.append(badge('PDF page moved','green'));if(r.contextStatus==='context_changed')tags.append(badge('Surrounding text changed','amber'));if(r.contextStatus==='context_unavailable')tags.append(badge('Context comparison unavailable'));title.append(tags);root.append(title,el('p','YOUR ORIGINAL QUOTE','eyebrow'),el('blockquote',r.quote,'original-quote'));if(r.note)root.append(el('p',`Your note: ${r.note}`,'small'));for(const w of r.warnings)root.append(el('p',w,'notice warning'));
 if(r.baselineStatus==='baseline_ambiguous'){root.append(el('p','The old text occurs more than once. A page hint does not resolve this. You can explicitly choose the intended occurrence; the original ambiguity stays in your report.','notice'));const l=el('label','Select the intended old occurrence');const select=el('select');select.append(new Option('Choose an occurrence…',''));r.before.forEach(o=>select.append(new Option(`PDF page ${o.page} · raw span ${o.start}–${o.end}`,o.id)));select.value=r.selectedOldId||'';select.addEventListener('change',()=>{state.selections.set(r.id,select.value);state.results[state.selected]=compareQuote(state.docs[0],state.docs[1],state.quotes[state.selected],{selectedOldId:select.value});showResults();});l.append(select);root.append(l);}
 const why={literal_match:'One occurrence of these exact words was located in searchable extracted revised text. Their presence does not establish unchanged meaning.',normalized_match:'One occurrence was located in searchable extracted revised text after whitespace normalization. Review the raw text and listed operations.',possible_changed_passage:'No accepted occurrence was located. These bounded, first-word-anchored suggestions may be related; they are not verified matches.',multiple_matches:'All accepted occurrences remain visible. Page proximity does not resolve which passage you intended.',not_located:'No accepted occurrence or supported suggestion was found. The passage may still be present in a form the extractor or candidate search cannot recognize.',source_unavailable:'Some revised text was unavailable or outside the supported scope. Visible occurrences remain below, but uniqueness and absence cannot be established.',not_evaluated:'Establish the quote in the old PDF first. Revision impact cannot be determined from a missing, incomplete or unresolved old baseline.'};root.append(el('p',why[r.targetStatus],'explanation'));
 if(r.candidates.length){const candidates=el('section',null,'candidate-section');candidates.append(el('h4','Possible changed passages'),el('p','Added words are green; missing words are struck through. These are suggestions, never accepted matches.','small muted'));for(const candidate of r.candidates){const diff=el('p',null,'word-diff');candidate.diff.forEach(d=>{diff.append(el(d.type==='insert'?'ins':d.type==='delete'?'del':'span',d.text),document.createTextNode(' '));});candidates.append(diff);showOccurrence(candidates,state.docs[1],candidate);}root.append(candidates);}
 const cols=el('div',null,'evidence-columns');for(const [label,items,doc]of[['Old source',r.before,state.docs[0]],['Revised source',r.after,state.docs[1]]]){const col=el('section');col.append(el('h4',`${label} · ${items.length} occurrence${items.length===1?'':'s'}`));if(!items.length)col.append(el('p','None located in available extracted text.','muted small'));for(const occ of items)showOccurrence(col,doc,occ);cols.append(col);}root.append(cols);}
function download(name,type,content){const url=URL.createObjectURL(new Blob([content],{type}));const a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export-json').addEventListener('click',()=>{if(state.results.length)download('quotecarry-report.json','application/json',JSON.stringify(buildReport(...state.docs,state.results),null,2)+'\n');});
$('export-html').addEventListener('click',()=>{if(state.results.length)download('quotecarry-report.html','text/html;charset=utf-8',reportHtml(buildReport(...state.docs,state.results)));});
quoteCards();
